name: juju-crashdump
version: git
summary: Gather logs and other debugging info from a Juju model
description: >
  The 'juju crashdump' plugin eases the collection of logs and
  other debugging info from a Juju model, and can even submit
  a bug to Launchpad with the data attached.  This makes it
  easy to debug a charm failure when you don't have direct
  access to the Juju model.
confinement: classic
grade: stable
base: core22
apps:
  juju-crashdump:
    command: bin/juju-crashdump
parts:
  juju-crashdump:
    plugin: python
    stage-packages:
      - python3-apport
      - jq
      - python3.10-minimal
      - libpython3.10-minimal
      - libpython3.10-stdlib
    python-packages:
      - pyyaml
      - ssh-agent-setup
    source: .
    build-attributes:
      - enable-patchelf
